<div class="clear"></div>



<div class="clear"></div>

<div id="footer-bg">
<div id="customHeading" style="
    background: #666668;
    padding:25px 0;
">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 style="font-size:30px" class="section-heading"><marquee><i class="fa fa-angle-double-left" aria-hidden="true"></i> RazorClean, The Circle of Trust. Save Money, Live RazorClean</marquee></h2>
            </div>
        </div>
    </div>
</div>
    <div id="footer" class="container_24 footer-top">
        <div id="footer_text" class="grid_20">
            <div>
                &copy; <?php echo date("Y")?> <strong><a href="<?php echo base_url()?>towing">RazorClean Towing</a></strong> Project By<a href="<?php echo base_url()?>"> RazorClean Inc.</a> </div>
        </div>
        <div class="back-to-top">
            <a href="#top">Back to Top</a>
        </div>
    </div>
</div>

<div class="clear"></div>

<script type='text/javascript' src='../s0.wp.com/<?php echo base_url() ?>media/landing-pages/towing/wp-content/js/devicepx-jetpack46a4.js?ver=201716'></script>
<script type='text/javascript' src='<?php echo base_url() ?>media/landing-pages/towing/wp-content/themes/u-design/sliders/cycle/jquery.cycle.all.min874f.js?ver=2.99'></script>
<script type='text/javascript' src='<?php echo base_url() ?>media/landing-pages/towing/wp-content/themes/u-design/sliders/cycle/jquery.easing.1.34e44.js?ver=1.3'></script>
<script type='text/javascript' src='<?php echo base_url() ?>media/landing-pages/towing/wp-content/themes/u-design/sliders/cycle/cycle3/cycle3_script8a54.js?ver=1.0.0'></script>
<script type='text/javascript' src='<?php echo base_url() ?>media/landing-pages/towing/wp-content/themes/u-design/scripts/prettyPhoto/js/jquery.prettyPhotoc6bd.js?ver=3.1.5'></script>
<script type='text/javascript' src='<?php echo base_url() ?>media/landing-pages/towing/wp-content/themes/u-design/scripts/prettyPhoto/custom_paramsc6bd.js?ver=3.1.5'></script>
<script type='text/javascript' src='<?php echo base_url() ?>media/landing-pages/towing/wp-content/themes/u-design/scripts/superfish-1.4.8/js/superfish.combined8a54.js?ver=1.0.0'></script>
<script type='text/javascript' src='<?php echo base_url() ?>media/landing-pages/towing/wp-content/themes/u-design/scripts/script5152.js?ver=1.0'></script>
<script type='text/javascript' src='<?php echo base_url() ?>media/landing-pages/towing/wp-content/themes/u-design/scripts/responsive/meanmenu/jquery.meanmenu.2.0.mind5f7.js?ver=2.0'></script>
<script type='text/javascript' src='<?php echo base_url() ?>media/landing-pages/towing/wp-content/themes/u-design/scripts/responsive/meanmenu/jquery.meanmenu.optionsd5f7.js?ver=2.0'></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<!--<script type='text/javascript' src='<?php echo base_url() ?>media/landing-pages/towing/wp-content/plugins/easy-contact-forms/easy-contact-forms-forms.1.4.90ed7.js?ver=3.8.20'></script>-->
<!-- Start Of Script Generated By cforms v14.6 [Oliver Seidel | www.deliciousdays.com] -->
<!-- End Of Script Generated By cforms -->
<script>
    jQuery(document).ready(function () {
    jQuery("#gform_2").submit(function (e) {
        e.preventDefault(); // avoid to execute the actual submit of the form.
        var url = "<?php echo base_url() ?>landing-pages/towing/callUs"; // the script where you handle the form input.
        //alert(url);
        jQuery.ajax({
            type: "POST",
            url: url,
            data: jQuery("#gform_2").serialize(), // serializes the form's elements.
            dataType: "json",
            success: function (data)
            {
                if (data.status === '0') {
                    jQuery("#rspstatus").html("Please provide required field");
                } else {
                    jQuery("#rspstatus").html(data.msg);
                    jQuery('#gform_2')[0].reset();
                }
            }
        });


    });
	
	 document.getElementById("myDiv").style.display="none";  // 5 seconds
	
    });

</script>
        
<!-- end wrapper-1 -->
</body>

<!-- Mirrored from eugenestowingcompany.com/ by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 21 Apr 2017 05:49:15 GMT -->

</html>